### PR TITLE
iriPropertyList

### LINKED ISSUE #100: iriPropertyList
There has been talk about creating a parallel to blankNodePropertyList (`[ ... ]`) but where the subject is some specified IRI, instead of a generated Blank Node. Most recently, this was raised by @bblfish recently in other fora. This might look like `[= ... ]`.

A proposed BNF might be `iriPropertyList ::= '[=' iri ';' predicateObjectList ']'`. (Alternatively, create a token IPLSTART ::= '[' WS* '=' and use `iriPropertyList ::= IPLSTART iri predicateObjectList ']'`. Also, add `iriPropertyList` as an alternative for `pathItem`.

For example, the example `[ :firstname "Ora" ] dc:wrote [ dc:title "Moby Dick" ] .` might be re-written as `[= :ora :firstname "Ora" ] dc:wrote [= :mobyDick dc:title "Moby Dick" ] .` which could generate the following triples:

```turtle
<http://example.com/ora> <http://example.com/firstname> "Ora" .
<http://example.com/ora> <http://purl.org/dc/elements/1.1/wrote> <http://example.com/mobyDick> .
<http://example.com/mobyDick> <http://purl.org/dc/elements/1.1/title> "Moby Dick" .
```

The provides a facility similar to JSON-LD for creating embedded statements.

Note that this entails the graph generated without special processing when `=` is interpreted as `owl:sameAs`:

```turtle
_:b0 <http://example.com/firstname> "Ora" .
_:b0 <http://www.w3.org/2002/07/owl#sameAs> <http://example.com/ora> .
_:b0 <http://purl.org/dc/elements/1.1/wrote> _:b1 .
_:b1 <http://purl.org/dc/elements/1.1/title> "Moby Dick" .
_:b1  <http://www.w3.org/2002/07/owl#sameAs> <http://example.com/mobyDick> .
```

I believe there are prior implementations of this, but I don't have a specific reference.

### PR DESCRIPTION
**Pull request by gkellogg**
* Update EBNF with iriPropertyList

Fixes #100.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/N3/pull/104.html" title="Last updated on Jun 30, 2022, 10:44 PM UTC (3506abb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/N3/104/b1b1a24...3506abb.html" title="Last updated on Jun 30, 2022, 10:44 PM UTC (3506abb)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
Failing on n3.ebnf reference; it may be that this needs to be a file with a known extension, such as `.txt`, or maybe it can be shut up. I'll check with the ReSpec group.

**Comment by gkellogg** [comment]
@william-vw Perhaps you can add an equivalent version of n3.g4 to this branch.

**Comment by william-vw** [comment]
> @william-vw Perhaps you can add an equivalent version of n3.g4 to this branch.

Will do this before our next CG meeting - would like to properly test it first, and integrate it into N3 editor.

**Comment by gkellogg** [comment]
I'll add some tests later today, based on those I outlined in https://github.com/w3c/N3/issues/100#issuecomment-1167812813.

**Pull request merged**
