### PR TITLE
WIP: Reasoner tests

### PR DESCRIPTION
**Pull request by gkellogg**
Work on updating the reasoning tests from the original SWAP tests.

Note, this may include tests for builtins we haven't specifically approved.

### CODE REVIEW

**Comment by william-vw** [comment]
Yes, but the more tests we have available, the better - we can always sort them out later.

**Comment by william-vw** [comment]
(note this PR is flagged as a draft so it cannot be merged)

**Comment by gkellogg** [comment]
Yes, I'll be adding more tests over the coming days, so didn't want to create too much merge work, but wanted to give visibility into what I'm doing for feedback.

**Comment by gkellogg** [comment]
There remain some tests untested and/or untestable:

* cwm_supports_simple cwm_string_roughly cwm_string_uriEncode all use unsupported builtins AFAIK.
* cwm_includes_conjunction – I haven't implemented log:conjunction just yet.
* cwm_includes_bnode – I haven't implement log:includes just yet.
* cwm_includes_conclusion_simple and cwm_unify_unify1 – I don't yet reason over bound formulae.
* cwm_reason_t6 – I haven't implemented math builtins just yet.
* cwm_list_builtin_generated_match – Reasoning using list reifications?

There are also holes for other defined builtins for which there aren't tests (or there are in the SWAP repo that haven't yet been integrated).

Anyway, this seem like a good checkpoint.

**Pull request merged**
